const RULES = {
    READ: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: true, ROLE_BASIC_VERIFICATEUR: true, ROLE_BASIC: true, ROLE_TECHNICIEN_OPERATEUR: true, ROLE_FEMME_CHAMBRE: false},
    CREATE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: true, ROLE_BASIC_VERIFICATEUR: true, ROLE_BASIC: true, ROLE_TECHNICIEN_OPERATEUR: true, ROLE_FEMME_CHAMBRE: false},
    UPDATE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: true, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: true, ROLE_FEMME_CHAMBRE: false},
    DELETE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: false, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: true, ROLE_FEMME_CHAMBRE: false},
    EQUIPEMENTS: {
        PAGE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: true, ROLE_FEMME_CHAMBRE: false},
        DEPLACER: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        UPDATE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
    },
    EQUIPEMENT: {
        PAGE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: true, ROLE_BASIC: true, ROLE_TECHNICIEN_OPERATEUR: true, ROLE_FEMME_CHAMBRE: false},
        CREATE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: true, ROLE_FEMME_CHAMBRE: false},
        UPDATE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: true, ROLE_FEMME_CHAMBRE: false},
        DELETE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        DEPLACER: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        SORTIR: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: true, ROLE_FEMME_CHAMBRE: false},
        UPLOAD_DOCUMENT: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        CREATE_MAINTENANCE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: true, ROLE_FEMME_CHAMBRE: false},
        CREATE_INTERVENTION_PREVENTIVE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: true, ROLE_FEMME_CHAMBRE: false},
        CREATE_DEMANDE_INTERVENTION: {ROLE_ADMIN: false, ROLE_SUPERVISEUR: false, ROLE_TECHNICIEN: false, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: true, ROLE_BASIC: true, ROLE_TECHNICIEN_OPERATEUR: true, ROLE_FEMME_CHAMBRE: false},
        CREATE_DEMANDE_INTERVENTION_MOBILE: {ROLE_ADMIN: false, ROLE_SUPERVISEUR: false, ROLE_TECHNICIEN: false, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: true, ROLE_BASIC: true, ROLE_TECHNICIEN_OPERATEUR: true, ROLE_FEMME_CHAMBRE: false},
        READ_SYNTHESE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        READ_CONSOMMABLES: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        CREATE_CONSOMMABLE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        ATTACHER_CONSOMMABLE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        CHECKER: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: true, ROLE_FEMME_CHAMBRE: false},
        REMPLACER_QR_CODE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: true, ROLE_FEMME_CHAMBRE: false},
    },
    LIEUX: {
        PAGE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: true, ROLE_FEMME_CHAMBRE: false},
        UPDATE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: true, ROLE_FEMME_CHAMBRE: false},
        DELETE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: false, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
    },
    SITES: {
        PAGE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
    },
    PIECE: {
        PAGE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        CREATE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        UPDATE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        DELETE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        CREATE_EQUIPEMENT: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: false, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        CREATE_MAINTENANCE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        CREATE_DEMANDE_INTERVENTION: {ROLE_ADMIN: false, ROLE_SUPERVISEUR: false, ROLE_TECHNICIEN: false, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: true, ROLE_BASIC: true, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        CHECK_LIEU: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: false, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
    },
    SITE: {
        PAGE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
    },
    BATIMENT: {
        PAGE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
    },
    REGISTRE_IMMOBILISATIONS: {
        PAGE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
    },
    INVENTAIRES: {
        PAGE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
    },
    MOUVEMENTS_EQUIPEMENTS: {
        PAGE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
    },
    CATEGORIES_EQUIPEMENTS: {
        PAGE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
    },
    CATEGORIE_EQUIPEMENT: {
        CREATE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        UPDATE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
    },
    CATEGORIES_LIEUX: {
        PAGE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
    },
    PLAN_INTERACTIF: {
        PAGE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: true, ROLE_FEMME_CHAMBRE: false},
        UPDATE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        DELETE_MARKER: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: false, ROLE_TECHNICIEN: false, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
    },
    TACHES: {
        PAGE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
    },
    VERIFICATIONS: {
        PAGE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: true, ROLE_FEMME_CHAMBRE: false},
    },
    PROGRESSION: {
        PAGE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: true, ROLE_FEMME_CHAMBRE: false},
    },
    STATISTIQUES_VERIFICATION: {
        PAGE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
    },
    CHECKS: {
        PAGE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: true, ROLE_BASIC_VERIFICATEUR: true, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: true, ROLE_FEMME_CHAMBRE: false},
    },
    DEMANDE_INTERVENTION: {
        PAGE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: true, ROLE_BASIC_VERIFICATEUR: true, ROLE_BASIC: true, ROLE_TECHNICIEN_OPERATEUR: true, ROLE_FEMME_CHAMBRE: false},
    },
    MAINTENANCES: {
        PAGE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: true, ROLE_FEMME_CHAMBRE: false},
        UPDATE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: true, ROLE_FEMME_CHAMBRE: false},
        DELETE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: false, ROLE_TECHNICIEN: false, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        TAB_EN_COURS: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: true, ROLE_FEMME_CHAMBRE: false},
        TAB_BLOQUANTES: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: true, ROLE_FEMME_CHAMBRE: false},
        TAB_URGENTES: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: true, ROLE_FEMME_CHAMBRE: false},
        TAB_NON_AFFECTES: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: true, ROLE_FEMME_CHAMBRE: false},
        TAB_MES_AFFECTATIONS: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: true, ROLE_FEMME_CHAMBRE: false},
        TAB_RETOUR_A_FAIRE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: true, ROLE_FEMME_CHAMBRE: false},
        TAB_RELANCES: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: true, ROLE_FEMME_CHAMBRE: false},
        TAB_SUPERVISOR: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: false, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: true, ROLE_FEMME_CHAMBRE: false},
        TAB_RESOLUES: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: true, ROLE_FEMME_CHAMBRE: false},
        TAB_TOUTES: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: true, ROLE_FEMME_CHAMBRE: false},
    },
    MAINTENANCE: {
        PAGE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: true, ROLE_FEMME_CHAMBRE: false},
        UPDATE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: true, ROLE_FEMME_CHAMBRE: false},
        DELETE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        DELETE_AFFECTATION: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: false, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        ACTIONS: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: true, ROLE_FEMME_CHAMBRE: false},
        CONSOMMATION: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: true, ROLE_FEMME_CHAMBRE: false},
        BON_DE_COMMANDE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: true, ROLE_FEMME_CHAMBRE: false},
        GESTION_FINANCIERE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        VALIDATION_SUPERVISOR: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: false, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        RELANCER: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: false, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: true, ROLE_FEMME_CHAMBRE: false},
        UPDATE_RAPPORT_CLOTURE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: false, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
    },
    MAINTENANCES_TACHES: {
        PAGE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: true, ROLE_FEMME_CHAMBRE: false},
    },
    RESERVES: {
        PAGE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
    },
    ACTIVITE_MAINTENANCE: {
        PAGE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: true, ROLE_BASIC: true, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        CREATE_MAINTENANCE_RELANCE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: true, ROLE_BASIC: true, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
    },
    PLANIFICATION: {
        PAGE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
    },
    STATISTIQUES_MAINTENANCE: {
        PAGE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
    },
    PLAN_MAINTENANCE_PREVENTIF: {
        PAGE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
    },
    GAMME_MAINTENANCE_PREVENTIF: {
        PAGE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
    },
    DEMANDE_CONSOMMABLES: {
        PAGE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: true, ROLE_BASIC: true, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        CREATE_CONSOMMABLE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
    },
    CONSOMMABLES: {
        PAGE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        CREATE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        DELETE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: false, ROLE_TECHNICIEN: false, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        CREATE_BON_DE_SORTIE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        CREATE_BON_DENTREE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
    },
    MOUVEMENTS_CONSOMMABLES: {
        PAGE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
    },
    CONSOMMABLE: {
        PAGE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        STOCK_AJUSTEMENT: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: false, ROLE_TECHNICIEN: false, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        DELETE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: false, ROLE_TECHNICIEN: false, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false}, // Added DELETE rule
    },
    GESTION_DE_STOCK: {
        SECTION: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: true, ROLE_BASIC: true, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
    },
    BONS: {
        PAGE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        CREATE_BON_DE_SORTIE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        CREATE_BON_DENTREE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
    },
    FICHES_DEMANDE_CONSOMMABLES: {
        PAGE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
    },
    FICHE_DEMANDE_CONSOMMABLES: {
        PAGE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
    },
    BONS_DE_COMMANDE: {
        PAGE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        DELETE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: false, ROLE_TECHNICIEN: false, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        CANCEL: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: false, ROLE_TECHNICIEN: false, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
    },
    TIERS: {
        PAGE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
    },
    TIER: {
        PAGE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        CREATE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        UPDATE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
    },
    CONTACTS: {
        PAGE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
    },
    CONTACT: {
        CREATE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        UPDATE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
    },
    CONTRATS: {
        PAGE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
    },
    CONTRAT: {
        PAGE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        CREATE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        UPDATE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
    },
    INTERVENTIONS: {
        PAGE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
    },
    INTERVENTION: {
        PAGE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        CREATE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        UPDATE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        VALIDATION: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        DELETE_ASSOCIATED_EQUIPEMENT: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: false, ROLE_TECHNICIEN: false, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
    },
    DASHBOARD: {
        PAGE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: true, ROLE_BASIC: true, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        CURATIF: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: true, ROLE_BASIC: true, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        PREVENTIF: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        CONSOMMABLE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        BON_DE_COMMANDE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
    },
    CALENDRIER: {
        PAGE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: true, ROLE_BASIC: true, ROLE_TECHNICIEN_OPERATEUR: true, ROLE_FEMME_CHAMBRE: false},
        UPDATE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        ONLY_PLANNING: {ROLE_ADMIN: false, ROLE_SUPERVISEUR: false, ROLE_TECHNICIEN: false, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: true, ROLE_BASIC: true, ROLE_TECHNICIEN_OPERATEUR: true, ROLE_FEMME_CHAMBRE: false},
    },
    PARAMETRES: {
        PAGE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: true, ROLE_BASIC: true, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        UPDATE_PASSWORD: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: false, ROLE_TECHNICIEN: false, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        UTILISATEURS: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        UPDATE_UTILISATEUR: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: false, ROLE_TECHNICIEN: false, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        CREATE_UTILISATEUR: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: false, ROLE_TECHNICIEN: false, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        ENTREPRISE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        UPDATE_ENTREPRISE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: false, ROLE_TECHNICIEN: false, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        MAINTENANCE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: false, ROLE_TECHNICIEN: false, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        LIEUX: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: false, ROLE_TECHNICIEN: false, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        ETIQUETTES: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: false, ROLE_TECHNICIEN: false, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        BONS_DE_COMMANDE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: false, ROLE_TECHNICIEN: false, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        CORPS_D_ETAT: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: false, ROLE_TECHNICIEN: false, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        EQUIPEMENTS: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: false, ROLE_TECHNICIEN: false, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
    },
    RELEVE_COMPTEUR: {
        CREATE_DATE_DEPASSEE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: false, ROLE_TECHNICIEN: false, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: true, ROLE_FEMME_CHAMBRE: false},
    },
    LANCEMENT: {
        PAGE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: true, ROLE_FEMME_CHAMBRE: false},
    },
    RECHERCHE_GENERALE: {
        CREATE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: false, ROLE_TECHNICIEN: false, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        UPDATE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: false, ROLE_TECHNICIEN: false, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        CREATE_DEMANDE_INTERVENTION: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: true, ROLE_BASIC: true, ROLE_TECHNICIEN_OPERATEUR: true, ROLE_FEMME_CHAMBRE: false},
        CREATE_MAINTENANCE: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: true, ROLE_BASIC: true, ROLE_TECHNICIEN_OPERATEUR: true, ROLE_FEMME_CHAMBRE: false},
        CREATE_CHECK: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: true, ROLE_BASIC_VERIFICATEUR: true, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: true, ROLE_FEMME_CHAMBRE: false},
        CREATE_SIGNALEMENT: {ROLE_ADMIN: false, ROLE_SUPERVISEUR: false, ROLE_TECHNICIEN: false, ROLE_SOUS_TRAITANT: false, ROLE_CHEF_EQUIPE: true, ROLE_BASIC_VERIFICATEUR: false, ROLE_BASIC: false, ROLE_TECHNICIEN_OPERATEUR: true, ROLE_FEMME_CHAMBRE: false},
        EQUIPEMENTS_READ: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: true, ROLE_BASIC_VERIFICATEUR: true, ROLE_BASIC: true, ROLE_TECHNICIEN_OPERATEUR: true, ROLE_FEMME_CHAMBRE: false},
        LIEUX_READ: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: true, ROLE_BASIC_VERIFICATEUR: true, ROLE_BASIC: true, ROLE_TECHNICIEN_OPERATEUR: true, ROLE_FEMME_CHAMBRE: false},
        MAINTENANCES_READ: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: true, ROLE_BASIC: true, ROLE_TECHNICIEN_OPERATEUR: true, ROLE_FEMME_CHAMBRE: false},
        CONTRATS_READ: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: true, ROLE_BASIC: true, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        TIERS_READ: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: true, ROLE_BASIC: true, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        CATEGORIES_READ: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: true, ROLE_BASIC: true, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        INTERVENTIONS_READ: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: true, ROLE_BASIC: true, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
        CONTACTS_READ: {ROLE_ADMIN: true, ROLE_SUPERVISEUR: true, ROLE_TECHNICIEN: true, ROLE_SOUS_TRAITANT: true, ROLE_CHEF_EQUIPE: false, ROLE_BASIC_VERIFICATEUR: true, ROLE_BASIC: true, ROLE_TECHNICIEN_OPERATEUR: false, ROLE_FEMME_CHAMBRE: false},
    }
};

export default {
	data: function(){
		return {
			rules: RULES
		};
	},
	created: function(){

	},
	methods: {
        /**
        * get authorized functionalities for a role
        *
        * @param String role
        */
        getRoleRules: function(role){

        },
        getRoleFromStorage : function(){

        },
        can:function(rule){
            if (this.$app){
				let pathToRule = rule.split(".");
                let role = this.$app.role;
				let ruleValue = this.rules;
				let ruleExist = true;
				pathToRule.forEach((partOfRule)=>{
					if(ruleExist && ruleValue.hasOwnProperty(partOfRule)) ruleValue = ruleValue[partOfRule];
					else ruleExist = false;
				});
				if(!ruleExist) console.log("-----------------------------> ! RULE EXIST", pathToRule);
                return ruleExist && ruleValue && ruleValue[role]===true;
            }else{
                // hack car restclient nest pas un composant donc je ne peux pas me servir de cette mixin
				let rules = RULES;
                var app = JSON.parse(sessionStorage.getItem('user'));
                if(!app) return true;
				let pathToRule = rule.split(".");
                let role = app.role;
				let ruleValue = rules;
				let ruleExist = true;
				pathToRule.forEach((partOfRule)=>{
					if(ruleExist && ruleValue.hasOwnProperty(partOfRule)) ruleValue = ruleValue[partOfRule];
					else ruleExist = false;
				});
                if(ruleExist && ruleValue && ruleValue[role]===true){ 
					return true;
				}else{
					alert("You can't "+ruleValue+" in accordance to your restrictions in this app");
					return false;
				}
            }
        }
    }
};
