---
to: _examples/<%= name %>.example.ts
---
import { ApiRequest } from "../src/core/ApiRequest";

/**
 * Example <%= name %> - Generated by Hygen
 * This demonstrates the pattern used in VerifgoodSDK
 */
export class <%= name %> extends ApiRequest {
  endpoint: string = '/api/<%= name.toLowerCase() %>';
  endpointSingleton: string = '/api/<%= name.toLowerCase().slice(0, -1) %>';

  // This service automatically inherits:
  // - getAll(metadatas: Metadatas)
  // - getById(id: number) 
  // - create(data: any)
  // - update(id: number, data: any)
  // - remove(id: number)

  // Add custom methods here as needed
}
